---
linters:
  disable-all: true
  enable:
    - asciicheck
    - errcheck
    - ineffassign
    - goimports
    - gosimple
    - govet
    - misspell
    - unconvert
    - unused


linters-settings:
  govet:
    disable:
      - printf # We disable printf check because we use a lot of dynamic formatting.